apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # C'est ici que la magie Helm opère !
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8090
          env:
            # On injecte les variables d'environnement pour Spring Boot
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.dbUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.dbUser }}
            - name: JWT_SECRET
              value: {{ .Values.secret.jwtKey }}
