#spring.datasource.url=jdbc:h2:mem:d-bank
#spring.h2.console.enabled=true
server.port=8086
spring.datasource.url=jdbc:mysql://localhost:3306/D-BANK?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

jwt.secret=5waa120514f2mee100291f20di62005m5waa120514f2mee100291f20di62005m
