server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Très important pour Angular : rediriger les requêtes 404 vers index.html
        # pour que le routeur d'Angular (les Guards, etc.) prenne le relais
        try_files $uri $uri/ /index.html;
    }
}
